import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Prism | Stitch-Generated Enterprise Landing Page Preview",
  description: "High-fidelity Stitch generated landing page with Apple design system.",
};

export default function StitchPreviewPage() {
  return (
    <div className="min-h-screen w-full bg-[#FAFAF9] flex flex-col">
      <div className="h-10 bg-[#1C1917] text-white px-4 flex items-center justify-between text-xs font-mono">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-sm bg-emerald-400"></span>
          <span>STITCH MCP HIGH-FIDELITY PREVIEW : PRISM LANDING PAGE</span>
        </div>
        <div className="flex items-center gap-3">
          <a
            href="/stitch/landing.html"
            target="_blank"
            rel="noopener noreferrer"
            className="text-sky-300 hover:underline"
          >
            Open Standalone HTML ↗
          </a>
          <span className="text-stone-500">|</span>
          <Link href="/" className="text-stone-300 hover:text-white">
            Return to App
          </Link>
        </div>
      </div>
      <iframe
        src="/stitch/landing.html"
        title="Prism Landing Page generated by Stitch"
        className="w-full flex-1 border-0 min-h-[calc(100vh-40px)]"
      />
    </div>
  );
}
