import { workflow, trigger, node, ifElse, newCredential, expr } from '@n8n/workflow-sdk';

/**
 * 🔷 PRISM 16, Knowledge Base Service (Supabase pgvector)
 * ----------------------------------------------------------------------------
 * Semantic retrieval against public.documents via the standard n8n
 * match_documents(...) RPC (PostgREST). The caller supplies the query embedding
 * (float[]), generated by the embedding-capable caller (agent vector-store
 * tool or a feature workflow), plus optional metadata filters.
 *
 * Credential: an n8n 'Supabase account' credential (Project URL + service role
 * secret). The HTTP Request node authenticates with it (apikey + Authorization
 * headers) and resolves the project host via {{ $credentials.host }}. If your
 * n8n build does not expose $credentials in the URL, replace the url with the
 * absolute PostgREST endpoint of the project and keep the credential auth.
 *
 * workflowInputs:
 *   connectorEnabled   boolean
 *   entitlement        boolean
 *   queryEmbedding     number[]   required                          
 *   query?             string     original text (kept for context)
 *   matchCount?        number     default 5
 *   filter?            object     JSON metadata filter (default {})
 */
const executeTrigger = trigger({
  type: 'n8n-nodes-base.executeWorkflowTrigger',
  version: 1.1,
  config: {
    name: 'Execute Workflow Trigger',
    parameters: {
      inputSource: 'workflowInputs',
      workflowInputs: {
        values: [
          { name: 'connectorEnabled', type: 'boolean' },
          { name: 'connectorPaused', type: 'boolean' },
          { name: 'entitlement', type: 'boolean' },
          { name: 'queryEmbedding', type: 'string' },
          { name: 'query', type: 'string' },
          { name: 'matchCount', type: 'number' },
          { name: 'filter', type: 'object' }
        ]
      }
    }
  }
});

const gateAndBuildBody = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Gate & Build RPC Body',
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: `
const item = $input.first()?.json || {};
const connectorEnabled = item.connectorEnabled !== false;
const connectorPaused = item.connectorPaused === true;
const entitlement = item.entitlement !== false;
const matchCount = Math.min(parseInt(item.matchCount, 10) || 5, 10);
const filter = (item.filter && typeof item.filter === 'object') ? item.filter : {};

if (connectorPaused) {
  return [{ json: { refused: true, reason: 'connector_paused', connectorId: 'internal.kb', records: [] } }];
}
if (connectorEnabled === false) {
  return [{ json: { refused: true, reason: 'connector_disabled', connectorId: 'internal.kb', records: [] } }];
}
if (entitlement === false) {
  return [{ json: { refused: true, reason: 'not_entitled', connectorId: 'internal.kb', records: [] } }];
}

let embedding = item.queryEmbedding;
if (typeof embedding === 'string') {
  try { embedding = JSON.parse(embedding); } catch (e) { embedding = null; }
}
if (!Array.isArray(embedding) || embedding.length === 0) {
  return [{ json: { refused: true, reason: 'missing_embedding', connectorId: 'internal.kb', records: [] } }];
}

return [{
  json: {
    refused: false,
    connectorId: 'internal.kb',
    query: String(item.query || ''),
    rpcBody: {
      query_embedding: embedding,
      match_count: matchCount,
      filter: filter
    }
  }
}];
`
    }
  }
});

const checkRefused = ifElse({
  version: 2.2,
  config: {
    name: 'Check Connector Gate',
    parameters: {
      conditions: {
        options: { caseSensitive: true, typeValidation: 'loose' },
        conditions: [
          {
            leftValue: expr('{{ $json.refused }}'),
            operator: { type: 'boolean', operation: 'true' }
          }
        ],
        combinator: 'and'
      }
    }
  }
});

const formatRefusal = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Return Clean Refusal',
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: `
const item = $input.first()?.json || {};
return [{ json: { refused: true, reason: item.reason || 'connector_unavailable', connectorId: 'internal.kb', total: 0, records: [] } }];
`
    }
  }
});

const callMatchDocuments = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'POST match_documents RPC',
    parameters: {
      method: 'POST',
      url: 'https://ejawdvxnddgkcgkasove.supabase.co/rest/v1/rpc/match_documents',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      specifyBody: 'json',
      jsonBody: expr('{{ JSON.stringify($json.rpcBody) }}'),
      options: { neverError: true }
    },
    credentials: {
      supabaseApi: newCredential('Supabase account')
    }
  }
});

const formatKbResults = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Format Knowledge Records',
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: `
const res = $input.first()?.json || {};
const gate = $('Gate & Build RPC Body').first()?.json || {};

if (res.code || res.message || (res.status && res.status >= 400)) {
  return [{
    json: {
      refused: false,
      error: String(res.message || res.code || 'supabase_error'),
      connectorId: 'internal.kb',
      total: 0,
      records: []
    }
  }];
}

const rawList = Array.isArray(res) ? res : [];
const records = rawList.map(function (r) {
  let meta = {};
  try { meta = typeof r.metadata === 'string' ? JSON.parse(r.metadata) : (r.metadata || {}); } catch (e) { meta = {}; }
  return {
    id: String(r.id || ''),
    content: r.content || '',
    metadata: meta,
    similarity: r.similarity !== undefined ? Number(r.similarity) : undefined
  };
});

return [{
  json: {
    refused: false,
    connectorId: 'internal.kb',
    query: gate.query || '',
    total: records.length,
    summary: 'Semantic matches retrieved from the organization knowledge base.',
    records: records
  }
}];
`
    }
  }
});

export default workflow('prism-knowledge-base-service', 'Prism - Knowledge Base Service')
  .add(executeTrigger)
  .to(gateAndBuildBody)
  .to(
    checkRefused
      .onTrue(formatRefusal)
      .onFalse(callMatchDocuments.to(formatKbResults))
  );
